### ISSUE TITLE
Plans to get astral 2.2 on conda?

### ISSUE THREAD

**Issue by AdamTheisen** [conda-forge/astral-feedstock#10]
Issue: Hello, I'm just curious if there are plans to update this feedstock to have the latest 2.2 version of astral.  Thanks!

**Comment by jbusecke** [comment]
Hi everyone, 

I am trying to set up the [GliderTools](https://github.com/GliderToolsCommunity/GliderTools) package with a conda-forge feedstock [here](https://github.com/conda-forge/staged-recipes/pull/14282) and am running into this problem as well. It seems like the builds are broken since [v2.0.1](https://github.com/conda-forge/astral-feedstock/pulls). Is there anything that I could do to help fix this? @hajapy

Many thanks

**Comment by jan-janssen** [comment]
Should be fixed with https://github.com/conda-forge/astral-feedstock/pull/9 or https://github.com/conda-forge/astral-feedstock/pull/14

**Comment by jan-janssen** [comment]
Done
